// packages/catlas-viewer-ol/src/main.tsx
import { QueryClientProvider } from "@tanstack/solid-query";
import { RouterProvider } from "@tanstack/solid-router";
import { render } from "solid-js/web";
import { createViewerQueryClient } from "./query-client.ts";
import { createViewerRouter } from "./router.ts";
import "../styled-system/styles.css";
import "./style.css";

const root = document.querySelector<HTMLDivElement>("#app");
if (!root) throw new Error("Viewer root element was not found.");

const queryClient = createViewerQueryClient();
const router = createViewerRouter();

render(
  () => (
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  ),
  root,
);

// packages/catlas-editor/src/main.tsx
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import { RouterProvider } from "@tanstack/react-router";
import { router } from "./routes.tsx";
import { initializeTheme, ThemeProvider } from "./components/editor/editor-theme.tsx";
import { TooltipProvider } from "./components/ui/tooltip.tsx";

initializeTheme();

const queryClient = new QueryClient();

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <ThemeProvider>
        <TooltipProvider delayDuration={300}>
          <RouterProvider router={router} />
        </TooltipProvider>
      </ThemeProvider>
    </QueryClientProvider>
  </StrictMode>,
);
